__default__:
  mem: "20000"
  time: "03:30:00"
  output: "results/logs_slurm/{rule}/{wildcards.wildcard}.log"
  cpus-per-task: 12
  nodes: 1

# snakemake --cluster-config config/cluster.yaml --cluster 'sbatch -t {cluster.time} --mem={cluster.mem} -c {cluster.cpus} -N {cluster.nodes} -o {cluster.output}' -j 40

# snakemake --cluster "sbatch -t {cluster.time} -p {cluster.partition} -N {cluster.nodes}" --cluster-config config/cluster.yaml --jobs 2 --latency-wait=15
