---
PATH_hg38: "/groups/wyattgrp/reference/hg38/hg38.fa"
PATH_bed: "resources/panel/1000012543_CHIP_Design_selection_results_Version2/capture_targets.bed"
PATH_bg: "resources/bg_error_rate/bg_error.tsv"
PATH_adapters: "resources/references/adapters.fa"
PATH_bets: "resources/betastasis/CLEANED_mutations_kidney_cancer_somatic.tsv"
DIR_sample_maps: "resources/sample_maps"
DIR_temp: "resources/TEMP"

# data files
DIR_raw_fastq: "results/data/fastq/raw"
DIR_merged_fastq: "results/data/fastq/merged"
DIR_masked_fastq: "results/data/fastq/masked"
DIR_extracted_fastq: "results/data/fastq/extracted"
DIR_trimmed_fastq: "results/data/fastq/trimmed"
DIR_trimmed_unpaired_fastq: "results/data/fastq/trimmed_unpaired"
DIR_bams: "results/data/bam"
DIR_recalibrated_base_scores: "results/base_recalc_info"

# fastqc reports 
DIR_merged_fastqc: "results/reports/fastqc/merged" # running fastqc right after merging individual fastqs from lanes
DIR_trimmed_fastqc: "results/reports/fastqc/trimmed" # running fastqc after masking and trimming

# metrics files 
DIR_insertsize_metrics: "results/metrics/insert_size"
DIR_markdup_metrics: "results/metrics/PICARD_markdup"
DIR_markdup_perc_metrics: "results/metrics/PICARD_markdup_perc"
DIR_depth_metrics: "results/metrics/depth"
DIR_depth_metrics_dedup: "results/metrics/depth_dedup"
DIR_mpileup: "results/metrics/mpileup"
DIR_complexity_metrics: "results/metrics/library_complexity"
DIR_dedup_metrics: "results/metrics/dedup"
DIR_readcounts_metrics: "results/metrics/read_counts"

# variant calling
DIR_varscan: "results/variant_calling/VarScan2"
VarScan_snv: "results/variant_calling/VarScan2/snv"
VarScan_indel: "results/variant_calling/VarScan2/indel"

DIR_Mutect: "results/variant_calling/Mutect2"
DIR_Haplotype: "results/variant_calling/Haplotype_caller"

DIR_Vardict: "results/variant_calling/Vardict"
DIR_Vardict_reformatted: "results/variant_calling/Vardict_reformatted"

# VarDict_snv_output: "results/variant_calling/Vardict/snv"
# VarDict_indel_output: "results/variant_calling/Vardict/indel"

# annotating variants from varscan
ANNOVAR_snv_input: "results/data/annovar_inputs/snv"
ANNOVAR_indel_input: "results/data/annovar_inputs/indel"
ANNOVAR_snv_output: "results/data/annovar_outputs/snv"
ANNOVAR_indel_output: "results/data/annovar_outputs/indel"
ANNOVAR_Vardict_input: "results/data/annovar_inputs/vardict"
ANNOVAR_Vardict_output: "results/data/annovar_outputs/vardict"
ANNOVAR_GATK_input: "results/data/annovar_inputs/haplotype_caller"
ANNOVAR_GATK_output: "results/data/annovar_outputs/haplotype_caller"


# filtering varscan2 results using R, based on thresholds etc
# PATH_SAVE_chip_variants: "results/variant_calling/VarScan2/finalized/{cohort_wildcard}/chip_variants.csv"
# PATH_validated_variants: "results/variant_calling/VarScan2/finalized/{cohort_wildcard}/validated_chip_variants.csv"

# figures 
DIR_insertsize_figures: "results/figures/insert_size"
DIR_insertsize_figures_PNG: "results/figures/insert_size_PNG"
