---
PATH_hg38: "/groups/wyattgrp/reference/hg38/hg38.fa"
PATH_bed: "resources/panel/1000012543_CHIP_Design_selection_results_Version2/capture_targets.bed"
PATH_bg: "resources/bg_error_rate/bg_error.tsv"
PATH_bets: "resources/betastasis/CLEANED_mutations_kidney_cancer_somatic.tsv"

# data files
DIR_raw_fastq: "results/data/fastq/raw"
DIR_merged_fastq: "results/data/fastq/merged"
DIR_masked_fastq: "results/data/fastq/masked"
DIR_trimmed_fastq: "results/data/fastq/trimmed" # trimmed fastqs saved here
DIR_bams: "results/data/bam"

# fastqc reports 
DIR_merged_fastqc: "results/reports/fastqc/merged" # running fastqc right after merging individual fastqs from lanes
DIR_trimmed_fastqc: "results/reports/fastqc/trimmed" # running fastqc after masking and trimming

# metrics files 
DIR_insertsize_metrics: "results/metrics/insert_size"
DIR_markdup_metrics: "results/metrics/PICARD_markdup"
DIR_depth_metrics: "results/metrics/depth"
DIR_mpileup: "results/metrics/mpileup"

# variant calling
DIR_varscan: "results/variant_calling/VarScan2"
VarScan_snv: "results/variant_calling/VarScan2/snv"
VarScan_indel: "results/variant_calling/VarScan2/indel"

DIR_Vardict: "results/variant_calling/Vardict"
# VarDict_snv_output: "results/variant_calling/Vardict/snv"
# VarDict_indel_output: "results/variant_calling/Vardict/indel"

# annotating variants from varscan
ANNOVAR_snv_input: "results/data/annovar_inputs/snv"
ANNOVAR_indel_input: "results/data/annovar_inputs/indel"
ANNOVAR_snv_output: "results/data/annovar_outputs/snv"
ANNOVAR_indel_output: "results/data/annovar_outputs/indel"
ANNOVAR_Vardict_input: "results/data/annovar_inputs/vardict"
ANNOVAR_Vardict_output: "results/data/annovar_outputs/vardict"

# filtering varscan2 results using R, based on thresholds etc
# PATH_SAVE_chip_variants: "results/variant_calling/VarScan2/finalized/{cohort_wildcard}/chip_variants.csv"
# PATH_validated_variants: "results/variant_calling/VarScan2/finalized/{cohort_wildcard}/validated_chip_variants.csv"

# figures 
DIR_insertsize_figures: "results/figures/insert_size"
DIR_insertsize_figures_PNG: "results/figures/insert_size_PNG"